apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlecloudstorage
spec:
  selector:
    matchLabels:
      app: google-storage-source
  template:
    metadata:
      labels:
        app: google-storage-source
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub
      containers:
      - name: subscriber
        image: gcr.io/triggermesh/googlecloudstorage
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: GOOGLE_CLOUD_PROJECT
          value: triggermesh
        - name: MY_SUBSCRIPTION_NAME
          value: bridgedemosub
